=== formatemp/tis_rendicontazione/TISDeroga2020/TracciatoXML/XSD_TIS_DEROGA_2020.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:nil="true">
	<xs:element name="tis">
	
		<xs:complexType>
			
			<xs:sequence>
				<xs:element name="istanza" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
							<xs:all>
							<xs:element type="xs:string" name="identificativoPratica" minOccurs="1" />
							<xs:element type="xs:string" name="denominazioneAPL" minOccurs="1" />
							<xs:element type="xs:string" name="ragioneSocialeUtilizzatore" minOccurs="1" />
							<xs:element name="partitaIvaUtilizzatore" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="(\d{11})|([A-Z]{6}\d{2}[A-Z][0-9A-Z]{2}[A-Z][0-9A-Z]{3}[A-Z])" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="codiceFiscaleUtilizzatore" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="(\d{11})|([A-Z]{6}\d{2}[A-Z][0-9A-Z]{2}[A-Z][0-9A-Z]{3}[A-Z])" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:string" name="codiceAtecoUtilizzatore" minOccurs="1" />
							<xs:element name="sedeUnitaProduttiva" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[A-Z][0-9A-Z]{3}" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="mensilitaAggiuntive" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0" />
										<xs:maxInclusive value="5" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="settoreRiferimento" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="ED" />
										<xs:enumeration value="NE" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sedeLegaleUtilizzatore">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[A-Z][0-9A-Z]{3}" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="giornateFruite" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="periodo" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:all>
													<xs:element name="totale" >
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="0" />
																<xs:maxInclusive value="31" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="anno">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="2020" />
																<xs:maxInclusive value="2020" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="mese">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="2" />
																<xs:maxInclusive value="12" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="distribuzioneOrarioAziendale">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="5" />
										<xs:maxInclusive value="7" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="utilizzatorePA" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="S" />
										<xs:enumeration value="N" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="autocertificazioneEmergenzaCausaleCovid19" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="S" />
										<xs:enumeration value="N" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="autocertificazioneSettimane" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="S" />
										<xs:enumeration value="N" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sogliaDimensionaleUno" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="S" />
										<xs:enumeration value="N" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sogliaDimensionaleDue" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="S" />
										<xs:enumeration value="N" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="dataRichiestaIncontroInvioInformativa" type="dataRichiestaIncontroInvioInformativaType" minOccurs="0" >
								
							</xs:element>    
							<xs:element name="esitoIncontro" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="A" />
										<xs:enumeration value="S" />
										<xs:enumeration value="N" />
										<xs:enumeration value="Z" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="note"  >
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="500"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="lavoratori">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="lavoratore" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:all>
													<xs:element name="annoRiferimento" minOccurs="1">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="2020" />
																<xs:maxInclusive value="2021" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="meseRiferimento" minOccurs="1">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="02|03|04|05|06|07|08|09|2|3|4|5|6|7|8|9|10|11|12" />
																<xs:maxLength value="2" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="codiceFiscale" minOccurs="1">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="([A-Z]{6}\d{2}[A-Z][0-9A-Z]{2}[A-Z][0-9A-Z]{3}[A-Z])" />
																<xs:length value="16" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element type="xs:string" name="nome" minOccurs="1" />
													<xs:element type="xs:string" name="cognome" minOccurs="1" />
													<xs:element name="tipologiaContratto" minOccurs="1">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="TD" />
																<xs:enumeration value="TI" />
																<xs:enumeration value="AP" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element type="dueCifreDecimali" name="retribuzioneMensileLorda" minOccurs="1" />
													<xs:element type="cinqueCifreDecimali" name="retribuzioneOrariaLordaDiFatto" minOccurs="1" />
													<xs:element name="sgraviAliquotaContributivaPrevidenziale" minOccurs="1">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="S" />
																<xs:enumeration value="N" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element type="dueCifreDecimali" name="percentualeSgraviAliquotaContributivaPrevidenziale" minOccurs="1" />
													<xs:element type="dueCifreDecimali" name="retribuzioneTisRiconosciuta" minOccurs="1" />
													<xs:element type="dueCifreDecimali" name="contribuzioneTisRiconosciuta" minOccurs="1" />
													<xs:element type="dueCifreDecimali" name="quotaRateiMensilitaAggiuntiveRetribuzione" minOccurs="1" />
													<xs:element type="dueCifreDecimali" name="quotaRateiMensilitaAggiuntiveContribuzione" minOccurs="1" />
													<xs:element type="dueCifreDecimali" name="quotaRateiRolPermessiFerieRetribuzione" minOccurs="1" />
													<xs:element type="dueCifreDecimali" name="quotaRateiRolPermessiFerieContribuzione" minOccurs="1" />
													<xs:element type="dueCifreDecimali" name="totaleOreTisRiconosciute" minOccurs="1" />
													<xs:element name="lavoratoreAlleDipendenze23Febbraio" minOccurs="1">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="S" />
																<xs:enumeration value="N" />
																<xs:enumeration value="Z" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="lavoratoreAlleDipendenze25Marzo" minOccurs="1">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="S" />
																<xs:enumeration value="N" />
																<xs:enumeration value="Z" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="lavoratoreAlleDipendenze13Luglio">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="S" />
																<xs:enumeration value="N" />
																<xs:enumeration value="Z" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="lavoratoreAlleDipendenze9Novembre" minOccurs="1">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="S" />
																<xs:enumeration value="N" />
																<xs:enumeration value="Z" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element type="dueCifreDecimali" name="divisoreContrattuale" minOccurs="1" />
												</xs:all>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
		
		</xs:complexType>
		<xs:unique name="uniqueIdentificativo">
			<xs:selector xpath="istanza" />
			<xs:field xpath="identificativoPratica" />
		</xs:unique>
		
	</xs:element>
	<xs:simpleType name="dueCifreDecimali" id="dueCifreDecimali">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits fixed="true" value="2" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="cinqueCifreDecimali" id="cinqueCifreDecimali">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits fixed="true" value="5" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dataRichiestaIncontroInvioInformativaType">
		<xs:union memberTypes="periodoPermessoDate">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value=""/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="periodoPermessoDate">
			<xs:restriction base="xs:date">
				<xs:minInclusive value="2020-02-23"/>
				<xs:maxInclusive value="2020-12-31"/>
			</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== formatemp/tis_rendicontazione/TISDeroga2020/TracciatoXML/XML_ESEMPIO_TIS_DEROGA_2020.xml
<tis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD_TIS_DEROGA_2020.xsd">   
	<istanza>  
		<identificativoPratica>1234</identificativoPratica> 
		<denominazioneAPL>APL DI ESEMPIO</denominazioneAPL>
		<ragioneSocialeUtilizzatore>ACME Company srl</ragioneSocialeUtilizzatore>
		<partitaIvaUtilizzatore>12345678901</partitaIvaUtilizzatore>
		<codiceFiscaleUtilizzatore>12345678901</codiceFiscaleUtilizzatore>
		<codiceAtecoUtilizzatore>00.00.00</codiceAtecoUtilizzatore> 
		<sedeUnitaProduttiva>H501</sedeUnitaProduttiva>
		<mensilitaAggiuntive>1</mensilitaAggiuntive>
		<settoreRiferimento>NE</settoreRiferimento>
		<autocertificazioneSettimane>S</autocertificazioneSettimane>
		<note></note>
		<sedeLegaleUtilizzatore>H501</sedeLegaleUtilizzatore>
		<giornateFruite> 
			<periodo>
				<totale>0</totale> 
				<anno>2020</anno>
				<mese>2</mese>
			</periodo>
			<periodo>
				<totale>20</totale>
				<anno>2020</anno>
				<mese>6</mese>
			</periodo>
		</giornateFruite>
		<distribuzioneOrarioAziendale>6</distribuzioneOrarioAziendale>
		<utilizzatorePA>N</utilizzatorePA>
		<autocertificazioneEmergenzaCausaleCovid19>S</autocertificazioneEmergenzaCausaleCovid19>
		<sogliaDimensionaleUno>N</sogliaDimensionaleUno>
		<sogliaDimensionaleDue>S</sogliaDimensionaleDue>
		<dataRichiestaIncontroInvioInformativa>2020-02-23</dataRichiestaIncontroInvioInformativa>
		<esitoIncontro>S</esitoIncontro> 
		<lavoratori>
			<lavoratore>
				<annoRiferimento>2020</annoRiferimento>
				<meseRiferimento>2</meseRiferimento> 
				<codiceFiscale>RSSMRA70H50H501M</codiceFiscale>
				<cognome>Rossi</cognome>
				<nome>Mario</nome>
				<tipologiaContratto>TD</tipologiaContratto>
				<sgraviAliquotaContributivaPrevidenziale>S</sgraviAliquotaContributivaPrevidenziale> 		
				<percentualeSgraviAliquotaContributivaPrevidenziale>0.00</percentualeSgraviAliquotaContributivaPrevidenziale> 		
				<retribuzioneMensileLorda>1792.00</retribuzioneMensileLorda> 
				<retribuzioneTisRiconosciuta>504.11</retribuzioneTisRiconosciuta> 
				<contribuzioneTisRiconosciuta>0</contribuzioneTisRiconosciuta> 
				<totaleOreTisRiconosciute>60</totaleOreTisRiconosciute> 
				<lavoratoreAlleDipendenze23Febbraio>S</lavoratoreAlleDipendenze23Febbraio>
				<lavoratoreAlleDipendenze25Marzo>S</lavoratoreAlleDipendenze25Marzo>
				<lavoratoreAlleDipendenze13Luglio>S</lavoratoreAlleDipendenze13Luglio>
				<lavoratoreAlleDipendenze9Novembre>Z</lavoratoreAlleDipendenze9Novembre>
				<retribuzioneOrariaLordaDiFatto>6.96001</retribuzioneOrariaLordaDiFatto> 
				<quotaRateiMensilitaAggiuntiveRetribuzione>10.00</quotaRateiMensilitaAggiuntiveRetribuzione> 
				<quotaRateiMensilitaAggiuntiveContribuzione>20.00</quotaRateiMensilitaAggiuntiveContribuzione> 
				<quotaRateiRolPermessiFerieRetribuzione>5.00</quotaRateiRolPermessiFerieRetribuzione> 
				<quotaRateiRolPermessiFerieContribuzione>7.00</quotaRateiRolPermessiFerieContribuzione> 
				<divisoreContrattuale>173.33</divisoreContrattuale>
			</lavoratore>
			<lavoratore>
				<annoRiferimento>2020</annoRiferimento>
				<meseRiferimento>3</meseRiferimento> 
				<codiceFiscale>RSSMRA70H50H501M</codiceFiscale>
				<cognome>Rossi</cognome>
				<nome>Mario</nome>
				<tipologiaContratto>TD</tipologiaContratto>
				<sgraviAliquotaContributivaPrevidenziale>S</sgraviAliquotaContributivaPrevidenziale> 		
				<percentualeSgraviAliquotaContributivaPrevidenziale>0.00</percentualeSgraviAliquotaContributivaPrevidenziale> 		
				<retribuzioneMensileLorda>1792.00</retribuzioneMensileLorda> 
				<retribuzioneTisRiconosciuta>504.11</retribuzioneTisRiconosciuta> 
				<contribuzioneTisRiconosciuta>0</contribuzioneTisRiconosciuta> 
				<totaleOreTisRiconosciute>60</totaleOreTisRiconosciute> 
				<lavoratoreAlleDipendenze23Febbraio>S</lavoratoreAlleDipendenze23Febbraio>
				<lavoratoreAlleDipendenze25Marzo>S</lavoratoreAlleDipendenze25Marzo>
				<lavoratoreAlleDipendenze13Luglio>S</lavoratoreAlleDipendenze13Luglio>
				<lavoratoreAlleDipendenze9Novembre>Z</lavoratoreAlleDipendenze9Novembre>
				<retribuzioneOrariaLordaDiFatto>6.96001</retribuzioneOrariaLordaDiFatto> 
				<quotaRateiMensilitaAggiuntiveRetribuzione>10.00</quotaRateiMensilitaAggiuntiveRetribuzione> 
				<quotaRateiMensilitaAggiuntiveContribuzione>20.00</quotaRateiMensilitaAggiuntiveContribuzione> 
				<quotaRateiRolPermessiFerieRetribuzione>5.00</quotaRateiRolPermessiFerieRetribuzione> 
				<quotaRateiRolPermessiFerieContribuzione>7.00</quotaRateiRolPermessiFerieContribuzione> 
				<divisoreContrattuale>173.33</divisoreContrattuale>
			</lavoratore>
			<lavoratore>
				<annoRiferimento>2020</annoRiferimento>
				<meseRiferimento>4</meseRiferimento> 
				<codiceFiscale>RSSMRA70H50H501M</codiceFiscale>
				<cognome>Rossi</cognome>
				<nome>Mario</nome>
				<tipologiaContratto>TD</tipologiaContratto>
				<sgraviAliquotaContributivaPrevidenziale>S</sgraviAliquotaContributivaPrevidenziale> 		
				<percentualeSgraviAliquotaContributivaPrevidenziale>0.00</percentualeSgraviAliquotaContributivaPrevidenziale> 		
				<retribuzioneMensileLorda>1792.00</retribuzioneMensileLorda> 
				<retribuzioneTisRiconosciuta>504.11</retribuzioneTisRiconosciuta> 
				<contribuzioneTisRiconosciuta>0</contribuzioneTisRiconosciuta> 
				<totaleOreTisRiconosciute>60</totaleOreTisRiconosciute> 
				<lavoratoreAlleDipendenze23Febbraio>S</lavoratoreAlleDipendenze23Febbraio>
				<lavoratoreAlleDipendenze25Marzo>S</lavoratoreAlleDipendenze25Marzo>
				<lavoratoreAlleDipendenze13Luglio>S</lavoratoreAlleDipendenze13Luglio>
				<lavoratoreAlleDipendenze9Novembre>Z</lavoratoreAlleDipendenze9Novembre>
				<retribuzioneOrariaLordaDiFatto>6.96001</retribuzioneOrariaLordaDiFatto> 
				<quotaRateiMensilitaAggiuntiveRetribuzione>10.00</quotaRateiMensilitaAggiuntiveRetribuzione> 
				<quotaRateiMensilitaAggiuntiveContribuzione>20.00</quotaRateiMensilitaAggiuntiveContribuzione> 
				<quotaRateiRolPermessiFerieRetribuzione>5.00</quotaRateiRolPermessiFerieRetribuzione> 
				<quotaRateiRolPermessiFerieContribuzione>7.00</quotaRateiRolPermessiFerieContribuzione> 
				<divisoreContrattuale>173.33</divisoreContrattuale>
			</lavoratore>
		</lavoratori>
	</istanza>
</tis>
